[package]
name = "vocab_vault"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.25"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
regex = "1.4.5"
