name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions/setup-rust@v2
      with:
        rust-version: stable
    - name: Build
      run: cargo build --release
    - name: Get binary
      run: cp target/release/vocab_vault ${{ github.workspace }}/vocab_vault.exe
    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.workspace }}/target/release/vocab_vault.exe
        tag_name: "v1.0.0" 
        title: "Release v1.0.0"  
        body: "Release v1.0.0"  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
