name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions/setup-rust@v2
      with:
        rust-version: stable
    - name: Build
      run: cargo build --release
    - name: Get binary
      run: cp target/release/vocab_vault ${{ github.workspace }}/vocab_vault.exe
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: vocab_vault
        path: ${{ github.workspace }}/vocab_vault.exe
        
