name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Get binary
      run: cp target/release/vocab_vault ${{ github.workspace }}
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: vocab_vault
        path: vocab_vault
